# Generated by Django 3.1.4 on 2021-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('typeofperson', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], max_length=10)),
            ],
        ),
    ]
