# Generated by Django 3.1.4 on 2021-07-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='address',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='details',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
