# Generated by Django 3.1.4 on 2021-07-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210720_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Address',
            new_name='address',
        ),
    ]
