# Generated by Django 3.1.4 on 2021-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20210720_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='pincode',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
