# Generated by Django 3.1.4 on 2021-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_details_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
